sudo: required

services:
  - docker

language: node_js
node_js:
  - '10'

cache:
  npm: true
  directories:
  - node_modules

install:
  - npx npm install

script:
  - npx npm run dev:lint

notifications:
  slack:
    secure: XLtKgXwYJFEk26VSPoglFVF7ogeTMPOdkS31lUHC2kd6Hv8HTmWaC7FFQRyG686TsqkohROTyAABj+uvS+Bjd0pDVuMPBJ144wd9fwBqhF46hqMFTNCpNpo6mkV1Ux+6GBkSqQlhwbFpwpyxkmspLSPgVUYDEUGD6HP+JYi6Xb0Uq7TiiBB/5UJQ9dMcb2nlKzHSSoIR4OA+Fhvgh/7vk5Q7rg9mxF7Q9t/xuo3a4yK0vScVVQEKCz50FRdqY11BfYs/FyVGMK0ANWV3B/BZcKpLZ4N+5V+BhBUKp/DtDCJe2I1Xj7QrIT1pkWNSGZlSSPPBYzAQdBmANj1hUe65XiAM9NNX8urdEsR63Xr617qkSUeVtJ1KVeQNMvf/mpAWrBVWc7JvZzoLIx6Iqo/MwBZmrPSWCcGXLfUTAh1kbD61YlejNlScmbvuJKk/46FnVpNHsKq7KaAGXytLSHCerJewQwAKE52HzyB4ST7lExwLMhzIyan6WCWPv0rfjzG9bV7p5dmetjOVMw2OddbsaOgWIXjDECOsAYzKUjFgNuOAD1dcSTpk7aQU4J8YosTd9eSaq4vN0vjcwgUQHA1QrspUGHfv3QgU2fn8qfOfzmmdPMP7gu+a0OWNv0WTqbVnXU/76a2BgOPHK9HFEdDchAYe7A/WEAAxVEYja8rtE3A=

