name: Publish a docker image

on:
  push:
    branches:
      - dev
    tags:
      - 'v*'

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v2

      - uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: docker/metadata-action@v3
        id: meta_node_extended
        with:
          images: ghcr.io/ambrosus/ambrosus-node-extended

      - uses: docker/build-push-action@v2
        with:
          file: Dockerfile
          push: true
          tags: ${{ steps.meta_node_extended.outputs.tags }}
          labels: ${{ steps.meta_node_extended.outputs.labels }}
